apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: quiz-frontend
  template:
    metadata:
      labels:
        app: quiz-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          env:
            - name: VITE_REACT_APP_API_URL
              value: {{ .Values.frontend.env.VITE_REACT_APP_API_URL }}
